version: '3.8'

services:
  client:
    build: ./client
    container_name: fastapi_client
    ports:
      - "8000:8000"          
    networks:
      - app_network
    depends_on:
      - server

  server:
    build: ./server
    container_name: grpc_server
    ports:
      - "50051:50051"        
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
