# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0c\x66ile_service\":\n\x11\x46ileUploadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x12\n\nchunk_data\x18\x02 \x01(\x0c\"%\n\x12\x46ileUploadResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x13\x46ileDownloadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"*\n\x14\x46ileDownloadResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\"&\n\x10\x46ileListResponse\x12\x12\n\nfile_names\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2\xfe\x01\n\x0b\x46ileService\x12Q\n\nUploadFile\x12\x1f.file_service.FileUploadRequest\x1a .file_service.FileUploadResponse(\x01\x12W\n\x0c\x44ownloadFile\x12!.file_service.FileDownloadRequest\x1a\".file_service.FileDownloadResponse0\x01\x12\x43\n\x0cGetFilesList\x12\x13.file_service.Empty\x1a\x1e.file_service.FileListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEUPLOADREQUEST']._serialized_start=31
  _globals['_FILEUPLOADREQUEST']._serialized_end=89
  _globals['_FILEUPLOADRESPONSE']._serialized_start=91
  _globals['_FILEUPLOADRESPONSE']._serialized_end=128
  _globals['_FILEDOWNLOADREQUEST']._serialized_start=130
  _globals['_FILEDOWNLOADREQUEST']._serialized_end=170
  _globals['_FILEDOWNLOADRESPONSE']._serialized_start=172
  _globals['_FILEDOWNLOADRESPONSE']._serialized_end=214
  _globals['_FILELISTRESPONSE']._serialized_start=216
  _globals['_FILELISTRESPONSE']._serialized_end=254
  _globals['_EMPTY']._serialized_start=256
  _globals['_EMPTY']._serialized_end=263
  _globals['_FILESERVICE']._serialized_start=266
  _globals['_FILESERVICE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
